
[build]  
  publish = "build/"
  command = "npx pnpm i --frozen-lockfile --ignore-scripts --store=node_modules/.pnpm-store && npx pnpm run build"

[build.environment]
# override netlify build with this workaround
  NPM_FLAGS = "--version"

# The following redirect is intended for use with most SPAs 
# that handle routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# [[headers]]
  # Define which paths this specific [[headers]] block will cover.
  # for = "/*"
  
  # [headers.values]
    # Multi-value headers are expressed with multi-line strings.
    # cache-control = '''
    # public,
    # max-age=31536000'''
