name: 'Deploy App Workflow'
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      branch:
        required: true
        type: string
      netlify_site_alias:
        required: false
        type: string
        default: ''
      isPreview:
        required: false
        type: boolean
        default: false
    secrets:
      app_env:
        required: true
      netlify_pat:
        required: true
      netlify_site_id:
        required: true
      # ssh_private_key:
      #   required: true
      # ssh_host:
      #   required: true
      # ssh_user:
      #   required: true

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    concurrency:
      cancel-in-progress: true
      group: ${{ inputs.environment }}
    steps:
      - name: Checkout ${{ inputs.branch }} branch
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.1

      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Set node environment variables
        run: echo ${{ secrets.app_env }} | openssl base64 -d -A -out .env

      - name: Build React App
        run: pnpm build

      - name: Deploy to Netlify (${{ github.ref_name }})
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './build'
          production-branch: main
          production-deploy: "${{ inputs.environment == 'production' }}"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: false
          overwrites-pull-request-comment: false
          netlify-config-path: ./netlify.toml
          github-deployment-environment: "${{ inputs.isPreview && 'pull request' || inputs.environment }}"
          alias: ${{ inputs.netlify_site_alias }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.netlify_pat }}
          NETLIFY_SITE_ID: ${{ secrets.netlify_site_id }}
        timeout-minutes: 10

      # - name: Check ${{ inputs.environment }} env
      #   run: |
      #     [[ "${{ secrets.ssh_host }}" == "DEV" ]] && echo "env isDev"
      #     [[ "${{ secrets.ssh_host }}" == "STAGING" ]] && echo "env isStaging"
      #     echo "environment ${{ inputs.environment }}"

      # how to setup https://zellwk.com/blog/github-actions-deploy/
      # 1. Generate keygen in server
      #    ssh-keygen -f ~/.ssh/github_actions/id_rsa_your_repo -t rsa -b 4096 -C "your_email@example.com"
      #
      # 2. Add public key to authorized_keys
      #    cat id_rsa_your_repo.pub >> .ssh/authorized_keys
      #
      # 3. copy your Private Key and paste it into Github Secrets.
      #    cat github_actions/id_rsa_your_repo >> Github Secrets -> ssh_private_key

      # to get the ref branch
      # take note that this is different from inputs.branch when executed from workflows with workflow_run
      # - name: Get the current branch name
      #   shell: bash
      #   run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
      #   id: extract_branch

      # - name: Install SSH Key
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.ssh_private_key }}
      #     known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      # - name: Adding Known Hosts
      #   run: ssh-keyscan -H ${{ secrets.ssh_host }} >> ~/.ssh/known_hosts

      # - name: Deploy app with rsync to ${{ inputs.environment }}
      #   run: rsync -avz --delete ./build/ ${{ secrets.ssh_user }}@${{ secrets.ssh_host }}:/home/ubuntu/apps/<repository name>/build/
