name: 'Manual deploy'
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        default: 'dev'
        options:
          - dev
          - staging

jobs:
  manual-deploy-dev:
    name: 'Deploy to Dev'
    if: ${{ github.event.inputs.environment == 'dev' }}
    uses: ./.github/workflows/deploy-app-workflow.yml
    with:
      environment: dev
      branch: ${{ github.ref }}
    secrets:
      app_env: ${{ secrets.APP_ENV }}
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      ssh_host: ${{ secrets.SSH_HOST }}
      ssh_user: ${{ secrets.SSH_USER }}

  manual-deploy-staging:
    name: 'Deploy to Staging'
    if: ${{ github.event.inputs.environment == 'staging' }}
    uses: ./.github/workflows/deploy-app-workflow.yml
    with:
      environment: staging
      branch: ${{ github.ref }}
    secrets:
      app_env: ${{ secrets.APP_ENV }}
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      ssh_host: ${{ secrets.SSH_HOST }}
      ssh_user: ${{ secrets.SSH_USER }}
