name: 'PR Tests'
on:
  pull_request:
    branches: [main, develop]

jobs:
  pr-lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.1

      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Run lint, type checks and tests
        run: |
          pnpm concurrently -g \
          "pnpm lint" \
          "pnpm check:types" \
          "pnpm test"

  pr-deploy-preview:
    if: github.event.pull_request.base.ref == 'develop'
    needs: [pr-lint-and-test]
    uses: ./.github/workflows/deploy-action.yml
    with:
      environment: dev
      branch: ${{ github.ref }}
      netlify_site_alias: preview-${{ github.event.number }}
      isPreview: true
    secrets:
      app_env: ${{ secrets.APP_ENV }}
      netlify_pat: ${{ secrets.NETLIFY_PAT }}
      netlify_site_id: ${{ secrets.NETLIFY_SITE_ID }}
